### ISSUE TITLE
User unbind and Ban throw attribute error

### ISSUE THREAD

**Issue by zayyadi** [Eudorajab1/jasmin_smsc_gui#8]
On getting to ban user or unbind them, the app throws an attribute error about flash not being an attribute of SimpleNamespace.

**To Reproduce**
1. Go to 'super Admin'
2. Click on 'click on user actions'
3. click on unbind or ban 
4. Internal server error in relation to the attribute error is thrown
![attrib](https://github.com/Eudorajab1/jasmin_smsc_gui/assets/32278136/b123b6bb-c639-4605-af12-a1fa907f33f6)

**Comment by Eudorajab1** [comment]
Will take a look and revert

**Comment by zayyadi** [comment]
I reverted back to py4web version 1.20210602.1 and the error disappeared.

**Comment by Eudorajab1** [comment]
Okay so I am in the process of updating to latest framework versions and
will push a new release shortly. Thanks for the feedback much appreciated.
